In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("preprocess.csv")

In [3]:
data.head()

Unnamed: 0  Reason1  Reason2  Reason3  Reason4  Reason for Absence  \
0           0        0        0        0        1                  26   
1           1        1        0        0        0                   0   
2           2        0        0        0        1                  23   
3           3        1        0        0        0                   7   
4           4        0        0        0        1                  23   

         Date  Transportation Expense  Distance to Work  Age  \
0  2015-07-07                     289                36   33   
1  2015-07-14                     118                13   50   
2  2015-07-15                     179                51   38   
3  2015-07-16                     279                 5   39   
4  2015-07-23                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Absenteeism Time in Hours  Month value  Day of week  
0                          4            7            1  
1                          0            7            1  
2                          2            7            2  
3                          4            7            3  
4                          2            7            3

In [4]:
targets = np.where(data["Absenteeism Time in Hours"]>data["Absenteeism Time in Hours"].median(),1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
data["Excessive Absenteeism"] = targets
data.head()

Unnamed: 0  Reason1  Reason2  Reason3  Reason4  Reason for Absence  \
0           0        0        0        0        1                  26   
1           1        1        0        0        0                   0   
2           2        0        0        0        1                  23   
3           3        1        0        0        0                   7   
4           4        0        0        0        1                  23   

         Date  Transportation Expense  Distance to Work  Age  \
0  2015-07-07                     289                36   33   
1  2015-07-14                     118                13   50   
2  2015-07-15                     179                51   38   
3  2015-07-16                     279                 5   39   
4  2015-07-23                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Absenteeism Time in Hours  Month value  Day of week  Excessive Absenteeism  
0                          4            7            1                      1  
1                          0            7            1                      0  
2                          2            7            2                      0  
3                          4            7            3                      1  
4                          2            7            3                      0

In [6]:
data = data.drop(["Absenteeism Time in Hours"], axis=1)
data= data.drop(["Date"], axis=1)
data= data.drop(["Daily Work Load Average","Distance to Work","Day of week"], axis=1)

In [7]:
data_final = data.copy()
data_final.head()

Unnamed: 0  Reason1  Reason2  Reason3  Reason4  Reason for Absence  \
0           0        0        0        0        1                  26   
1           1        1        0        0        0                   0   
2           2        0        0        0        1                  23   
3           3        1        0        0        0                   7   
4           4        0        0        0        1                  23   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Month value  Excessive Absenteeism  
0            7                      1  
1            7                      0  
2            7                      0  
3            7                      1  
4            7                      0

In [8]:
x = data_final.iloc[:,:-1]
y = data_final.iloc[:,-1]

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [10]:
scaled_x = scaler.fit(x)
scaled_x = scaler.transform(x)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(scaled_x,y,test_size=0.2, random_state=42)

### Logistic regression

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [13]:
reg = LogisticRegression()

In [14]:
reg.fit(x_train,y_train)

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
reg.score(x_train,y_train)

0.7517857142857143

#### Finding intercept and coeff

In [16]:
reg.intercept_

array([-0.11671273])

In [17]:
reg.coef_

array([[-0.1446686 ,  0.74404151,  0.05536491,  0.51910764, -1.05605512,
         1.12510051,  0.50954405, -0.23055435,  0.18618033, -0.07204854,
         0.30171515, -0.38114615,  0.11743401]])

In [18]:
feature_names = x.columns.values

In [19]:
summary_table = pd.DataFrame(columns=['Feature_names'],data=feature_names)
summary_table['Coefficient'] = np.transpose(reg.coef_)  #transpose as nd arrays are rows not columns
summary_table

Feature_names  Coefficient
0               Unnamed: 0    -0.144669
1                  Reason1     0.744042
2                  Reason2     0.055365
3                  Reason3     0.519108
4                  Reason4    -1.056055
5       Reason for Absence     1.125101
6   Transportation Expense     0.509544
7                      Age    -0.230554
8          Body Mass Index     0.186180
9                Education    -0.072049
10                Children     0.301715
11                    Pets    -0.381146
12             Month value     0.117434

In [20]:
summary_table.index = summary_table.index +1
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature_names  Coefficient
0                Intercept    -0.116713
1               Unnamed: 0    -0.144669
2                  Reason1     0.744042
3                  Reason2     0.055365
4                  Reason3     0.519108
5                  Reason4    -1.056055
6       Reason for Absence     1.125101
7   Transportation Expense     0.509544
8                      Age    -0.230554
9          Body Mass Index     0.186180
10               Education    -0.072049
11                Children     0.301715
12                    Pets    -0.381146
13             Month value     0.117434

In [21]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature_names  Coefficient  Odds_ratio
0                Intercept    -0.116713    0.889841
1               Unnamed: 0    -0.144669    0.865309
2                  Reason1     0.744042    2.104423
3                  Reason2     0.055365    1.056926
4                  Reason3     0.519108    1.680527
5                  Reason4    -1.056055    0.347825
6       Reason for Absence     1.125101    3.080526
7   Transportation Expense     0.509544    1.664532
8                      Age    -0.230554    0.794093
9          Body Mass Index     0.186180    1.204639
10               Education    -0.072049    0.930486
11                Children     0.301715    1.352176
12                    Pets    -0.381146    0.683078
13             Month value     0.117434    1.124607

In [22]:
summary_table.sort_values('Odds_ratio',ascending=False)

Feature_names  Coefficient  Odds_ratio
6       Reason for Absence     1.125101    3.080526
2                  Reason1     0.744042    2.104423
4                  Reason3     0.519108    1.680527
7   Transportation Expense     0.509544    1.664532
11                Children     0.301715    1.352176
9          Body Mass Index     0.186180    1.204639
13             Month value     0.117434    1.124607
3                  Reason2     0.055365    1.056926
10               Education    -0.072049    0.930486
0                Intercept    -0.116713    0.889841
1               Unnamed: 0    -0.144669    0.865309
8                      Age    -0.230554    0.794093
12                    Pets    -0.381146    0.683078
5                  Reason4    -1.056055    0.347825

#### Prediction of accuracy

In [23]:
reg.score(x_test,y_test)

0.75

#### Save the model

In [24]:
import pickle

In [25]:
with open('model','wb') as file:
    pickle.dump(reg,file)